/**
 * MyOS Knowledge — tone matching.
 *
 * Reads the user's recent Sent-folder emails, shows them to the LLM as
 * style samples, and asks for a short cover note in the same voice.
 *
 * Used by /brief/decide delegate + autonomousExecutor delegate + draft_reply
 * so forwarded emails don't scream "auto-generated by a system".
 *
 * The MD's Sent samples are cached per-user in memory for 15 min to avoid
 * re-fetching 6 Gmail messages on every delegation.
 */
import { getSentSamples } from '../gmailService';
import { callLLM } from '../llmRouter';

interface ToneCache {
  samples: Array<{ subject: string; body: string; to: string }>;
  fetchedAt: number;
}
const toneCache = new Map<number, ToneCache>();
const TTL_MS = 15 * 60 * 1000;

async function samplesFor(userId: number): Promise<Array<{ subject: string; body: string; to: string }>> {
  const cached = toneCache.get(userId);
  if (cached && Date.now() - cached.fetchedAt < TTL_MS) return cached.samples;
  const r = await getSentSamples(userId, 6).catch(() => ({ samples: [] as any[] }));
  toneCache.set(userId, { samples: r.samples, fetchedAt: Date.now() });
  return r.samples;
}

/**
 * Generate a short cover note in the user's voice for forwarding an email.
 * Falls back to a conservative neutral line if LLM / samples unavailable.
 */
export async function composeForwardNote(params: {
  userId: number;
  userName?: string;
  delegateeName?: string;
  originalSender: string;
  originalSubject: string;
  originalSnippet: string;
  mdNote?: string;  // optional MD-provided free text
}): Promise<string> {
  const {
    userId, userName, delegateeName, originalSender,
    originalSubject, originalSnippet, mdNote,
  } = params;

  const samples = await samplesFor(userId).catch(() => []);

  // If we have no samples AND no LLM, produce a minimal neutral forward
  const fallback = () => {
    const greeting = delegateeName ? `Hi ${delegateeName.split(' ')[0]},\n\n` : '';
    const ask = mdNote ? `${mdNote}\n\n` : 'Please handle this one.\n\n';
    const signoff = userName ? `Thanks,\n${userName.split(' ')[0]}` : 'Thanks';
    return greeting + ask + signoff;
  };

  if (samples.length < 2) return fallback();

  const toneSamples = samples
    .slice(0, 4)
    .map((s, i) => `Sample ${i + 1}\nTo: ${s.to}\nSubject: ${s.subject}\n---\n${s.body}`)
    .join('\n\n────\n\n');

  const basePrompt = `You write brief email forward cover-notes in a specific person's voice.
You will be given 2-6 samples of the user's own sent emails. Study the
tone: formality, opening salutation, how concise they are, signoff.
Then write a forward cover-note for the new email below.

RULES:
- NEVER mention that this is an automated system, "MyOS", "Brain", "AI",
  or any tool. It must read like the user wrote it themselves.
- Keep it short: greeting, one or two sentences of ask, signoff.
- Do NOT re-summarize the original email — recipient will see it below.
- Match the user's tone exactly (warm vs terse, formal vs casual).
- If the MD provided a specific note, incorporate it; otherwise a standard
  "please handle this" / "please take forward" style works.
- Output ONLY the cover-note body (no "Subject:" line, no JSON wrapping,
  no explanations).`;

  const { withUserPrompts } = await import('./userPromptService');
  const system = await withUserPrompts(basePrompt, userId, 'delegation');

  const user = `User's voice samples:

${toneSamples}

────────────────

Now write the forward cover-note for THIS email:

Recipient: ${delegateeName ?? 'colleague'}
Original sender: ${originalSender}
Original subject: ${originalSubject}
Original preview: ${originalSnippet.slice(0, 300)}
${mdNote ? `MD wants to say: ${mdNote}` : ''}

Cover-note (in the user's voice):`;

  try {
    const r = await callLLM(system, user, { maxTokens: 200, userId, purpose: 'tone_email_forward' });
    const text = r.text.trim();
    // Strip accidental "Subject:" or labels the model might emit
    return text.replace(/^(Cover[- ]?note:|Subject:).*$/gim, '').trim() || fallback();
  } catch {
    return fallback();
  }
}

/**
 * Compose a short, contextual deadline-inquiry email in the user's voice
 * for a delegatee. Replaces the old static "Quick question: when can you
 * have this back?" template that read identically across every delegate
 * and every item — felt like a program, not a brain.
 *
 * Inputs:
 *  - userId: for tone samples
 *  - userName: signoff
 *  - delegateeName: greeting personalisation
 *  - itemTitle: WHAT we're asking about (the brain should reference this)
 *  - itemDescription: optional context the user may have left when delegating
 *
 * Output: HTML body (greeting + 1–2 sentences + signoff). Subject is
 * computed by the caller so it can match the original thread.
 */
export async function composeDeadlineInquiry(params: {
  userId: number;
  userName?: string | null;
  delegateeName?: string | null;
  itemTitle: string;
  itemDescription?: string | null;
}): Promise<string> {
  const { userId, userName, delegateeName, itemTitle, itemDescription } = params;

  const samples = await samplesFor(userId).catch(() => []);

  const escapeHtml = (s: string): string => s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  const fallback = (): string => {
    const greet = delegateeName ? `Hi ${delegateeName.split(' ')[0]},` : 'Hi,';
    const sign = userName ? userName.split(' ')[0] : '';
    return [
      `<p>${greet}</p>`,
      `<p>Quick one — for "${escapeHtml(itemTitle)}", when can you have it back? A target date helps me plan around it.</p>`,
      `<p>Reply with a date or a phrase ("next Friday", "in 5 days") and I'll work to it.</p>`,
      sign ? `<p>Thanks,<br/>${escapeHtml(sign)}</p>` : `<p>Thanks!</p>`,
    ].join('\n');
  };

  if (samples.length < 2) return fallback();

  const toneSamples = samples
    .slice(0, 4)
    .map((s, i) => `Sample ${i + 1}\nTo: ${s.to}\nSubject: ${s.subject}\n---\n${s.body}`)
    .join('\n\n────\n\n');

  const basePrompt = `You write short emails in a specific person's voice.
You'll be given 2-6 of the user's own sent emails as tone samples. Mirror
their style: formality, openings, signoff. Then write a brief deadline
inquiry to a colleague who has been delegated something but hasn't given
a target date yet.

RULES:
- Reference the specific item being asked about — do NOT use a generic
  "Quick question" that fits any context. The colleague should feel
  like the user wrote a personal note about THIS task.
- Keep it short: greeting, one or two sentences asking for a target
  date, signoff. Two short paragraphs max.
- Match the user's tone (warm vs terse, formal vs casual).
- NEVER mention "MyOS", "Brain", "AI", or any tool. It must read like
  the user wrote it themselves.
- Output HTML body only. Use <p> for paragraphs. No <html>/<body>
  wrappers, no Subject line, no JSON.`;

  const userPrompt = `User's voice samples:

${toneSamples}

────────────────

Now write a deadline-inquiry email for THIS task:

Recipient: ${delegateeName ?? 'colleague'}
Task title: ${itemTitle}
${itemDescription ? `Context: ${itemDescription.slice(0, 400)}` : ''}

Write the email body in HTML (<p> paragraphs):`;

  const { withUserPrompts } = await import('./userPromptService');
  const system = await withUserPrompts(basePrompt, userId, 'delegation');

  try {
    const r = await callLLM(system, userPrompt, { maxTokens: 220, userId, purpose: 'tone_deadline_inquiry' });
    const text = r.text.trim();
    // If the model returned plain text (no <p>), wrap it.
    const html = /<p[\s>]/i.test(text) ? text : text.split(/\n\n+/).map((p) => `<p>${escapeHtml(p)}</p>`).join('\n');
    return html || fallback();
  } catch {
    return fallback();
  }
}

// ═══════════════════════════════════════════════════════════════════════════
//  WhatsApp reply tone — different style, different sample pool
// ═══════════════════════════════════════════════════════════════════════════
//
//  WhatsApp replies are SHORT, NO greeting, NO signature, lowercase-common,
//  often in Roman Urdu for Pakistani MDs. Samples must come from the SAME
//  chat (not a generic sent pool) so Brain mirrors how you talk to THIS
//  person specifically — a reply to your wife reads nothing like a reply
//  to a vendor. Samples are cached per (userId, chatId) for 15 min.

interface WaToneCacheEntry {
  samples: string[];
  fetchedAt: number;
}
const waToneCache = new Map<string, WaToneCacheEntry>();

async function waSamplesFor(userId: number, chatId: string): Promise<string[]> {
  const key = `${userId}:${chatId}`;
  const cached = waToneCache.get(key);
  if (cached && Date.now() - cached.fetchedAt < TTL_MS) return cached.samples;
  try {
    const { fetchSentSamplesForChat } = await import('../whatsapp/UserWebjsProvider');
    const samples = await fetchSentSamplesForChat(userId, chatId, 30);
    waToneCache.set(key, { samples, fetchedAt: Date.now() });
    return samples;
  } catch { return []; }
}

/**
 * Compose a short WhatsApp reply in the MD's exact style for THIS chat.
 * Falls back to a generic one-liner if samples unavailable.
 *
 * Uses THREE inputs:
 *  1. MD's prior sent messages in this chat → tone reference
 *  2. Recent 10-turn transcript (both sides) → context for what
 *     ambiguous messages like "On it", "yes", "sure" actually refer to
 *  3. If meeting intent detected → next free calendar slots so the reply
 *     can propose concrete times instead of "let me check"
 *
 * No greeting, no signature. Matches language (English / Roman Urdu) and
 * emoji usage from prior sent messages in the same chat.
 */
export async function composeWhatsAppReply(params: {
  userId: number;
  chatId: string;
  incomingText: string;
  senderName?: string;
  mdNote?: string;
  threadContext?: Array<{ from: 'me' | 'them'; text: string; timestamp: number }>;
}): Promise<string> {
  const { userId, chatId, incomingText, senderName, mdNote, threadContext } = params;

  const samples = await waSamplesFor(userId, chatId).catch(() => []);

  // Read context from whatever the caller supplied, or pull it now
  let thread = threadContext;
  if (!thread || thread.length === 0) {
    try {
      const { fetchThreadContext } = await import('../whatsapp/UserWebjsProvider');
      thread = await fetchThreadContext(userId, chatId, 10);
    } catch { thread = []; }
  }

  // Meeting intent detection — if incoming looks like a scheduling ask,
  // fetch next few free calendar slots so we can propose concrete times.
  const meetingIntent = detectMeetingIntent(incomingText, thread ?? []);
  let calendarBlock = '';
  if (meetingIntent) {
    try {
      const slots = await suggestMeetingSlots(userId, meetingIntent.durationMin);
      if (slots.length > 0) {
        calendarBlock = `\n\nYour calendar next 48h (free windows in PKT):\n${slots.map((s) => `- ${s}`).join('\n')}\n\nPropose 2 of these in the reply.`;
      }
    } catch { /* fall back to generic */ }
  }

  const fallback = () => {
    if (mdNote) return mdNote;
    const lower = incomingText.toLowerCase();
    if (/\?$/.test(incomingText.trim())) return 'let me check and get back';
    if (/\b(thanks|thank you|shukria)\b/.test(lower)) return 'welcome';
    return 'noted, getting back shortly';
  };

  if (samples.length < 2 && (!thread || thread.length < 2)) return fallback();

  const toneBlock = samples
    .slice(-10)
    .map((s, i) => `[${i + 1}] ${s}`)
    .join('\n');

  const threadBlock = (thread ?? [])
    .map((t) => `${t.from === 'me' ? 'YOU:' : (senderName ? senderName.toUpperCase() + ':' : 'THEM:')} ${t.text}`)
    .join('\n');

  const basePrompt = `You write WhatsApp replies in a specific person's voice, using the conversation so far to ground the reply.

RULES — non-negotiable:
- SHORT: 1–2 sentences max. Often just one line. Never a paragraph.
- NO greeting unless the samples consistently open that way.
- NO signature, no signoff.
- Match LANGUAGE from samples exactly — Roman Urdu, English, code-switched — mirror it.
- Match CASING — if samples are lowercase, reply lowercase.
- Match EMOJI frequency from samples (often zero).
- READ THE TRANSCRIPT. If the incoming is ambiguous ("On it", "yes", "sure", "done"), figure out what it refers to from the prior turns. Acknowledge the right thing, or if MD needs to take the next step, surface that naturally.
- If the incoming is a scheduling/meeting ask and free calendar slots are provided, propose 2 specific times (not "let me check"). Keep it a single line.
- NEVER mention AI, "Brain", "MyOS", or automation.
- Output ONLY the reply text. No quotes, no explanation.`;

  const { withUserPrompts } = await import('./userPromptService');
  const system = await withUserPrompts(basePrompt, userId, 'whatsapp_reply');

  const user = `MD's texting style (their prior messages in this chat, latest at bottom):
${toneBlock || '(no samples yet)'}

────

Recent conversation (both sides):
${threadBlock || '(no context)'}

────

${senderName ? `${senderName} just sent:` : 'They just sent:'}
"${incomingText}"
${mdNote ? `\nMD wants to say: ${mdNote}` : ''}${calendarBlock}

Write the reply (one line, MD's voice):`;

  try {
    const r = await callLLM(system, user, { maxTokens: 100, userId, purpose: 'tone_whatsapp_reply' });
    const text = r.text.trim().replace(/^["'`]|["'`]$/g, '');
    return text || fallback();
  } catch {
    return fallback();
  }
}

// ── Meeting-intent detection + calendar slot suggestion ───────────────

interface MeetingIntent { durationMin: number }

function detectMeetingIntent(incomingText: string, thread: Array<{ from: string; text: string }>): MeetingIntent | null {
  const blob = [incomingText, ...thread.slice(-4).map((t) => t.text)].join(' ').toLowerCase();
  const hit =
    /\b(meet|meeting|call|catch up|discuss|get on a call|zoom|g\s*meet|google meet|schedule)\b/.test(blob) ||
    /\b(kab|kab mile|milte|milna|milen|kab free)\b/.test(blob) || // Roman Urdu
    /\bcan we\b.*\b(meet|talk|call|sync|chat)\b/.test(blob);
  if (!hit) return null;
  const durMatch = blob.match(/(\d+)\s*(min|minute|minutes|hr|hour|hours)/);
  let dur = 30;
  if (durMatch) {
    const n = parseInt(durMatch[1], 10);
    dur = /hr|hour/.test(durMatch[2]) ? n * 60 : n;
  }
  return { durationMin: dur };
}

/**
 * Return a short list of human-readable free slots over the next 48h
 * working hours (10 AM – 7 PM PKT), filtered against the MD's calendar.
 * Best-effort: returns [] if no calendar connector.
 */
async function suggestMeetingSlots(userId: number, durationMin: number): Promise<string[]> {
  try {
    const { getEvents } = await import('../calendarService');
    const now = new Date();
    const end = new Date(now.getTime() + 48 * 60 * 60 * 1000);
    const r = await getEvents(userId, now, end, 50).catch(() => ({ events: [] as any[] }));
    const busy = (r.events || [])
      .filter((e: any) => e.start && e.end)
      .map((e: any) => ({
        start: new Date(e.start),
        end: new Date(e.end),
      }));

    const out: string[] = [];
    const cursor = new Date(now);
    // round up to next half-hour mark
    cursor.setMinutes(cursor.getMinutes() < 30 ? 30 : 60, 0, 0);
    while (cursor < end && out.length < 3) {
      const hour = cursor.getHours();
      if (hour >= 10 && hour < 19) {
        const slotEnd = new Date(cursor.getTime() + durationMin * 60 * 1000);
        const overlaps = busy.some((b) => !(b.end <= cursor || b.start >= slotEnd));
        if (!overlaps) {
          const today = new Date();
          const isToday = cursor.toDateString() === today.toDateString();
          const isTomorrow = cursor.toDateString() === new Date(today.getTime() + 24 * 60 * 60 * 1000).toDateString();
          const dayLabel = isToday ? 'today' : isTomorrow ? 'tomorrow' : cursor.toLocaleDateString('en-GB', { weekday: 'short' });
          const timeLabel = cursor.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
          out.push(`${dayLabel} ${timeLabel}`);
        }
      }
      cursor.setMinutes(cursor.getMinutes() + 30);
    }
    return out;
  } catch { return []; }
}
