# ═══════════════════════════════════════════════════════════════
# Outputs — values needed by TMCAI codebase (.env)
# ═══════════════════════════════════════════════════════════════

output "project_id" {
  value = var.project_id
}

# Pub/Sub
output "pubsub_topics" {
  value = var.use_pubsub ? module.pubsub.topic_names : {}
}

# BigQuery
output "bigquery_dataset_decisions" {
  value = module.bigquery.decisions_dataset_id
}

output "bigquery_dataset_shadow" {
  value = module.bigquery.shadow_dataset_id
}

output "bigquery_dataset_steering" {
  value = module.bigquery.steering_dataset_id
}

# Cloud Storage
output "golden_dataset_bucket" {
  value = module.storage.golden_dataset_bucket
}

output "bq_staging_bucket" {
  value = module.storage.bq_staging_bucket
}

output "backup_bucket" {
  value = module.storage.backup_bucket
}

# IAM
output "agent_worker_sa_email" {
  value = module.iam.agent_worker_sa_email
}

output "bq_exporter_sa_email" {
  value = module.iam.bq_exporter_sa_email
}

output "api_sa_email" {
  value = module.iam.api_sa_email
}

# Cloud Functions
output "bq_export_function_url" {
  value = module.functions.bq_export_function_url
}

# Secrets
output "secret_ids" {
  value = module.secrets.secret_ids
}

# ───────────────────────────────────────
# .env snippet for TMCAI server
# ───────────────────────────────────────
output "env_snippet" {
  value = <<-EOT
    # === GCP Config (auto-generated by Terraform) ===
    GCP_PROJECT_ID=${var.project_id}
    GCP_REGION=${var.region}
    BQ_DATASET_DECISIONS=${module.bigquery.decisions_dataset_id}
    BQ_DATASET_SHADOW=${module.bigquery.shadow_dataset_id}
    BQ_DATASET_STEERING=${module.bigquery.steering_dataset_id}
    GCS_GOLDEN_DATASET_BUCKET=${module.storage.golden_dataset_bucket}
    GCS_BQ_STAGING_BUCKET=${module.storage.bq_staging_bucket}
    GCS_BACKUP_BUCKET=${module.storage.backup_bucket}
    BQ_EXPORT_FUNCTION_URL=${module.functions.bq_export_function_url}
    USE_PUBSUB=${var.use_pubsub}
  EOT
}
