-- ════════════════════════════════════════════════════════════════════
-- Backfill connector_types catalog.
-- ════════════════════════════════════════════════════════════════════
--
-- The original catalog was seeded via `prisma db push` in early dev
-- (2026-04-11), before formal migrations existed. Tenants that came
-- online via `prisma migrate` afterwards never received it — their
-- connector_types table holds only the rows added by later migrations
-- (notion, whatsapp_personal). The Connectors page is then empty
-- because there are no connector_types to enable.
--
-- This migration is idempotent (`ON CONFLICT (slug) DO NOTHING`) — it
-- only inserts rows that don't already exist. Tenants that already
-- have the full catalog see no change.
--
-- Pairs with 20260504_enable_default_personal_connectors which then
-- enables every active personal connector for every tenant.

INSERT INTO connector_types (id, slug, name, description, category, scope, auth_method, config_schema, capabilities, icon, is_active, created_at) VALUES
  ('ct_gmail',                 'gmail',                 'Gmail',                 'Read, search, and send emails via Google Gmail',                                                                          'email',         'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'gmail',         true, NOW()),
  ('ct_outlook',               'outlook',               'Microsoft Outlook',     'Read and send emails via Outlook / O365',                                                                                  'email',         'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'outlook',       true, NOW()),
  ('ct_google_calendar',       'google_calendar',       'Google Calendar',       'View events, create meetings, manage RSVPs',                                                                              'calendar',      'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'google_calendar', true, NOW()),
  ('ct_outlook_calendar',      'outlook_calendar',      'Outlook Calendar',      'View and create events via Microsoft Calendar',                                                                            'calendar',      'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'outlook_calendar', true, NOW()),
  ('ct_google_tasks',          'google_tasks',          'Google Tasks',          'Sync tasks bidirectionally with open items',                                                                              'tasks',         'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'google_tasks',  true, NOW()),
  ('ct_ms_todo',               'ms_todo',               'Microsoft To Do',       'Sync tasks with Microsoft To Do',                                                                                          'tasks',         'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'ms_todo',       true, NOW()),
  ('ct_todoist',               'todoist',               'Todoist',               'Sync tasks, projects, and priorities',                                                                                    'tasks',         'personal',       'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'todoist',       true, NOW()),
  ('ct_trello',                'trello',                'Trello',                'Sync cards and boards',                                                                                                    'tasks',         'personal',       'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'trello',        true, NOW()),
  ('ct_whatsapp',              'whatsapp',              'WhatsApp',              'Send and receive WhatsApp messages',                                                                                       'messaging',     'personal',       'webhook',         '{}'::jsonb, '["read","write"]'::jsonb, 'whatsapp',      true, NOW()),
  ('ct_telegram',              'telegram',              'Telegram',              'Send and receive Telegram messages',                                                                                       'messaging',     'personal',       'bot_token',       '{}'::jsonb, '["read","write"]'::jsonb, 'telegram',      true, NOW()),
  ('ct_google_chat',           'google_chat',           'Google Chat',           'Read and send Google Chat messages',                                                                                       'chat',          'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'google_chat',   true, NOW()),
  ('ct_slack',                 'slack',                 'Slack',                 'Read DMs, mentions, and send messages',                                                                                    'chat',          'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'slack',         true, NOW()),
  ('ct_ms_teams',              'ms_teams',              'Microsoft Teams',       'Read and send Teams messages',                                                                                             'chat',          'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'ms_teams',      true, NOW()),
  ('ct_google_drive_personal', 'google_drive_personal', 'Google Drive',          'Access personal Google Drive files',                                                                                       'drive',         'personal',       'oauth2',          '{}'::jsonb, '["read"]'::jsonb,         'google_drive',  true, NOW()),
  ('ct_onedrive_personal',     'onedrive_personal',     'OneDrive',              'Access personal OneDrive files',                                                                                           'drive',         'personal',       'oauth2',          '{}'::jsonb, '["read"]'::jsonb,         'onedrive',      true, NOW()),
  ('ct_linkedin_personal',     'linkedin_personal',     'LinkedIn',              'Read profile, connections, messages',                                                                                      'social',        'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'linkedin',      true, NOW()),
  ('ct_twitter_x',             'twitter_x',             'Twitter / X',           'Read mentions, DMs, and post',                                                                                             'social',        'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'twitter',       true, NOW()),
  ('ct_zoom',                  'zoom',                  'Zoom',                  'View and schedule Zoom meetings',                                                                                          'meetings',      'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'zoom',          true, NOW()),
  ('ct_notion_personal',       'notion_personal',       'Notion',                'Read and create personal Notion pages',                                                                                    'notes',         'personal',       'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'notion',        true, NOW()),
  ('ct_sap',                   'sap',                   'SAP ERP',               'Financial monitoring, project data, AR/AP, risks',                                                                         'erp',           'organizational', 'credentials',     '{}'::jsonb, '["read","write"]'::jsonb, 'sap',           true, NOW()),
  ('ct_odoo',                  'odoo',                  'Odoo ERP/CRM',          'CRM pipeline, invoicing, projects, HR',                                                                                    'erp',           'organizational', 'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'odoo',          true, NOW()),
  ('ct_bigquery',              'bigquery',              'BigQuery',              'Query business data from BigQuery',                                                                                        'data_warehouse','organizational', 'service_account', '{}'::jsonb, '["read"]'::jsonb,         'bigquery',      true, NOW()),
  ('ct_google_drive_org',      'google_drive_org',      'Google Drive (Org)',    'Organization shared Drive',                                                                                                'drive',         'organizational', 'service_account', '{}'::jsonb, '["read","write"]'::jsonb, 'google_drive',  true, NOW()),
  ('ct_google_sheets',         'google_sheets',         'Google Sheets',         'Read and write shared sheets',                                                                                             'spreadsheets',  'organizational', 'service_account', '{}'::jsonb, '["read","write"]'::jsonb, 'google_sheets', true, NOW()),
  ('ct_salesforce',            'salesforce',            'Salesforce',            'Leads, opportunities, accounts',                                                                                           'crm',           'organizational', 'oauth2',          '{}'::jsonb, '["read","write"]'::jsonb, 'salesforce',    true, NOW()),
  ('ct_hubspot',               'hubspot',               'HubSpot',               'Contacts, deals, companies, tickets',                                                                                      'crm',           'organizational', 'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'hubspot',       true, NOW()),
  ('ct_jira',                  'jira',                  'Jira',                  'Issues, sprints, boards, backlogs',                                                                                        'project_mgmt',  'organizational', 'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'jira',          true, NOW()),
  ('ct_notion_org',            'notion_org',            'Notion (Org)',          'Organization Notion workspace',                                                                                            'project_mgmt',  'organizational', 'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'notion',        true, NOW()),
  ('ct_zendesk',               'zendesk',               'Zendesk',               'Support tickets and satisfaction',                                                                                         'support',       'organizational', 'api_key',         '{}'::jsonb, '["read"]'::jsonb,         'zendesk',       true, NOW()),
  ('ct_github',                'github',                'GitHub',                'Repos, issues, PRs, deployments',                                                                                          'dev',           'organizational', 'oauth2',          '{}'::jsonb, '["read"]'::jsonb,         'github',        true, NOW()),
  ('ct_vertex_ai',             'vertex_ai',             'Vertex AI / Known',     'Org-wide email intelligence',                                                                                              'intelligence',  'organizational', 'service_account', '{}'::jsonb, '["read"]'::jsonb,         'vertex_ai',     true, NOW()),
  ('ct_ess_hr',                'ess_hr',                'HR / ESS System',       'Appraisals, leave, attendance, payroll',                                                                                   'hr',            'organizational', 'api_key',         '{}'::jsonb, '["read","write"]'::jsonb, 'hr',            true, NOW())
ON CONFLICT (slug) DO NOTHING;
